Listing FROSKA
HerculesDeFiLabs/tokens-list pull request #13
Opened 2024-09-10 09:42 UTC by Froska-Dev

2024-09-10 16:48 UTC, waliair requested changes
@Froska-Dev could you update the Twitter address with the correct Twitter profile link?

`  "twitter": "https://www.froska.io/",`

2024-09-11 13:10 UTC, Froska-Dev commented
@waliair Updated kindly review.
Sorry for the mix up

2024-09-13 19:43 UTC, Froska-Dev commented
any update @waliair

2024-09-16 13:54 UTC, waliair approved these changes

2024-09-16 13:55 UTC, merged